# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-24T15:08:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Type(Enum):
    fs = 'fs'


class FsRepositorySpec(BaseModel):
    type: Literal['fs']
    location: str = Field(..., description='Directory holding the repository.')
    encryption_key: str | None = Field(
        default=None, description='32-byte repository key, hex. Never returned.'
    )


class Type1(Enum):
    s3 = 's3'


class S3RepositorySpec(BaseModel):
    type: Literal['s3']
    endpoint: str = Field(
        ..., description='Scheme and host, e.g. https://s3.us-east-1.amazonaws.com'
    )
    bucket: str
    region: str = Field(
        ..., description='Signing region. GCS and R2 accept `auto` or `us-east-1`.'
    )
    prefix: str | None = Field(
        default=None,
        description='Key prefix, so one bucket can hold several repositories.',
    )
    access_key_id: str
    secret_access_key: str = Field(..., description='Never returned by any endpoint.')
    session_token: str | None = Field(
        default=None, description='For temporary STS credentials. Never returned.'
    )
    path_style: bool | None = Field(
        default=True,
        description='Bucket in the path (`/bucket/key`), which MinIO and most self-hosted stores require. False uses a virtual host.\n',
    )
    encryption_key: str | None = Field(
        default=None, description='32-byte repository key, hex. Never returned.'
    )


class Type2(Enum):
    fs = 'fs'
    s3 = 's3'


class Spec(BaseModel):
    """
    The repository's non-secret configuration. Secrets are omitted rather than masked.

    """

    type: Type2 | None = None
    location: str | None = None
    endpoint: str | None = None
    bucket: str | None = None
    region: str | None = None
    prefix: str | None = None
    access_key_id: str | None = None
    path_style: bool | None = None
    encrypted: bool | None = Field(
        default=None, description='Whether objects are sealed with a repository key.'
    )


class RegisteredRepository(BaseModel):
    repository: str | None = None
    spec: Spec | None = Field(
        default=None,
        description="The repository's non-secret configuration. Secrets are omitted rather than masked.\n",
    )


class CreateSnapshotRequest(BaseModel):
    """
    Exactly one of `index` or `namespace`.
    """

    index: str | None = Field(default=None, description='A physical index to capture.')
    namespace: str | None = Field(
        default=None,
        description='A namespace to capture. Only a promoted namespace can be: a pooled one shares its segments with every other namespace in its pool.\n',
    )
    allow_shared_pool: bool | None = Field(
        default=False,
        description='Acknowledge that snapshotting a `__pool_N` index captures every namespace stored in it.\n',
    )


class RestoreRequest(BaseModel):
    signer_public_key: str | None = Field(
        default=None,
        description="The signer's ed25519 public key, hex. Must be the key the snapshot names as its signer; both facts are checked.\n",
    )
    allow_unverified_signer: bool | None = Field(
        default=False,
        description='Restore a snapshot this node cannot attribute to itself or to a known peer.\n',
    )
    allow_overwrite_live_index: bool | None = Field(
        default=False,
        description='Roll a LIVE index back to this snapshot. Without it, restoring over an index that is currently serving is refused with `409`: the restore would replace what it serves, and the next query would simply return older data with nothing to say it happened.\n',
    )


class Kind(Enum):
    snapshot = 'snapshot'
    restore = 'restore'
    cleanup = 'cleanup'


class State(Enum):
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'


class SnapshotJob(BaseModel):
    id: str | None = None
    kind: Kind | None = None
    state: State | None = None
    repository: str | None = None
    snapshot: str | None = None
    index: str | None = Field(
        default=None, description='The index or namespace the job is acting on.'
    )
    started_at_ms: int | None = None
    finished_at_ms: int | None = None
    result: dict[str, Any] | None = Field(
        default=None, description='What the operation produced, once it succeeded.'
    )
    error: str | None = Field(default=None, description='Why it failed.')


class NamespaceKey(BaseModel):
    """
    The namespace's BYOK key record, when it has one. Carries the WRAPPED DEK only — sealed under the tenant's KEK, which no node ever holds — because without it the restored `_source` could not be decrypted even by the rightful tenant: re-registering a key mints a different DEK. A restore applies it only when it is at least as new as what the node already knows, so an old snapshot cannot undo a revoke.

    """

    generation: int | None = None
    keyed: bool | None = None
    revoked: bool | None = None
    wrapped_dek: str | None = Field(
        default=None, description="Hex. Useless without the tenant's KEK."
    )


class Claim(BaseModel):
    claim_unit_id: int | None = None
    manifest_id: str | None = None
    epoch: int | None = None
    doc_count: int | None = None
    segment_hashes: list[str] | None = None


class SnapshotDescriptor(BaseModel):
    """
    What a snapshot IS: the manifests and segment hashes it captured, signed by the node that took it. The signature covers every segment hash, so a repository cannot substitute content.

    """

    snapshot: str | None = None
    index_name: str | None = None
    namespace: str | None = Field(
        default=None, description='Set when this is a namespace snapshot.'
    )
    namespace_key: NamespaceKey | None = Field(
        default=None,
        description="The namespace's BYOK key record, when it has one. Carries the WRAPPED DEK only — sealed under the tenant's KEK, which no node ever holds — because without it the restored `_source` could not be decrypted even by the rightful tenant: re-registering a key mints a different DEK. A restore applies it only when it is at least as new as what the node already knows, so an old snapshot cannot undo a revoke.\n",
    )
    index_id: str | None = None
    index_generation: int | None = None
    created_at_ms: int | None = None
    signer_node_id: str | None = None
    segment_count: int | None = None
    total_bytes: int | None = None
    signature: str | None = None
    signature_verified: bool | None = Field(
        default=None,
        description='Whether this node checked the signature against a key it independently trusts.\n',
    )
    signature_note: str | None = Field(
        default=None,
        description='Why the signature could not be verified, when it could not.',
    )
    claims: list[Claim] | None = None


class NamespaceKeyStatus(BaseModel):
    namespace: str = Field(..., description='The namespace this status describes')
    encrypted: bool = Field(
        ..., description='True when a wrapped DEK is registered for this namespace'
    )
    unlocked: bool = Field(
        ..., description='True when this node holds the unwrapped DEK in memory'
    )
    registered: bool | None = Field(
        default=None,
        description='Present on PUT — true when this call newly registered the key',
    )


class Type3(Enum):
    """
    Stable error type. Part of the v1 contract — new types may
    be added, existing types will not be removed or renamed.

    """

    validation_error = 'validation_error'
    unsupported_capability = 'unsupported_capability'
    unsupported_engine = 'unsupported_engine'
    index_not_found = 'index_not_found'
    document_not_found = 'document_not_found'
    index_already_exists = 'index_already_exists'
    field_not_found = 'field_not_found'
    schema_error = 'schema_error'
    unauthorized = 'unauthorized'
    internal_error = 'internal_error'
    rate_limited = 'rate_limited'
    unauthenticated = 'unauthenticated'
    forbidden = 'forbidden'
    repository_not_found = 'repository_not_found'
    snapshot_not_found = 'snapshot_not_found'
    repository_error = 'repository_error'
    shared_pool = 'shared_pool'
    namespace_not_snapshottable = 'namespace_not_snapshottable'
    job_in_progress = 'job_in_progress'
    unverified_signer = 'unverified_signer'


class ErrorBody(BaseModel):
    """
    The structured error body. `type` and `reason` are always present,
    on every route and from every layer — typed `/v1` handlers, the
    `/v1/memory/*` family, and the middleware (rate limiting, RBAC).
    Read `reason`.


    `message` is a deprecated alias carrying identical text, emitted so
    that callers written before `reason` existed keep working. It is
    not part of the forward contract and will be removed in a future
    major version.

    """

    type: Type3 = Field(
        ...,
        description='Stable error type. Part of the v1 contract — new types may\nbe added, existing types will not be removed or renamed.\n',
    )
    reason: str = Field(
        ...,
        description='Human-readable description. Always present. This is the field to read.\n',
    )
    message: str | None = Field(
        default=None,
        deprecated=True,
        description='Deprecated alias for `reason`, carrying identical text. Present so callers written before `reason` existed keep working; it will be removed in a future major version. Do not read it in new code.\n',
    )
    detail: dict[str, Any] | None = Field(
        default=None,
        description='Structured detail for capability and engine errors.\nShape varies by error type.\n',
    )


class DistanceMetric(Enum):
    """
    Distance function (dense_vector and multi_vector only)
    """

    cosine = 'cosine'
    dot_product = 'dot_product'
    l2 = 'l2'


class Quantization(Enum):
    """
    On-disk vector quantization (dense_vector only). `none` stores
    float32; `int8` is ~4x smaller, `int4` ~8x, `binary` ~32x.

    """

    none = 'none'
    int8 = 'int8'
    int4 = 'int4'
    binary = 'binary'


class Format(Enum):
    """
    Date format (date fields only). Default: strict_date_optional_time.
    Controls output format in _source. Ingest always accepts both
    ISO-8601 strings (nanosecond precision) and epoch milliseconds
    regardless of format. Internal precision is nanoseconds.

    """

    strict_date_optional_time = 'strict_date_optional_time'
    epoch_millis = 'epoch_millis'
    epoch_nanos = 'epoch_nanos'


class FieldType(Enum):
    """
    Public field type names. Engine support varies — unsupported types
    fail deterministically at engine-capability validation.

    """

    text = 'text'
    keyword = 'keyword'
    integer = 'integer'
    long = 'long'
    float = 'float'
    double = 'double'
    date = 'date'
    boolean = 'boolean'
    geo_point = 'geo_point'
    geo_shape = 'geo_shape'
    point = 'point'
    shape = 'shape'
    dense_vector = 'dense_vector'
    multi_vector = 'multi_vector'
    graph_edge = 'graph_edge'


class IndexDocumentRequest(BaseModel):
    """
    Document body. Top-level keys (except _id) are field values
    that must conform to the index schema.

    """

    model_config = ConfigDict(
        extra='allow',
    )
    field_id: str | None = Field(
        default=None,
        alias='_id',
        description='Optional document ID. If omitted, the system generates one.\n',
    )


class Ack(Enum):
    """
    Durability level actually reached, which is what `wait_for`
    asked for unless the wait timed out. Always present.

    """

    accepted = 'accepted'
    accepted_durably = 'accepted_durably'
    visible_for_search = 'visible_for_search'


class IndexDocumentResponse(BaseModel):
    field_id: str = Field(
        ..., alias='_id', description='Document ID (provided or generated)'
    )
    ack: Ack = Field(
        ...,
        description='Durability level actually reached, which is what `wait_for`\nasked for unless the wait timed out. Always present.\n',
    )
    timed_out: bool | None = Field(
        default=None,
        description='Present and true when `wait_for` timed out before the requested\nlevel was reached — the write was accepted, but `ack` is weaker\nthan asked for.\n',
    )


class GetDocumentResponse(BaseModel):
    field_id: str = Field(..., alias='_id')
    field_source: dict[str, Any] = Field(
        ..., alias='_source', description='The stored document fields'
    )


class BulkIndexRequest(BaseModel):
    documents: list[IndexDocumentRequest] = Field(..., min_length=1)


class Ack1(Enum):
    """
    Durability level reached for the whole batch. Always present.

    """

    accepted = 'accepted'
    accepted_durably = 'accepted_durably'
    visible_for_search = 'visible_for_search'


class BulkItemResult(BaseModel):
    field_id: str = Field(..., alias='_id')
    status: int = Field(..., description='HTTP-style status code for this item')
    error: ErrorBody | None = None


class BulkStreamItem(BaseModel):
    field_id: str | None = Field(
        default=None, alias='_id', description='Document ID (absent for parse errors)'
    )
    status: int = Field(..., description='HTTP-style status code for this item')
    error: ErrorBody | None = None
    seq: int = Field(
        ..., description='0-based position of this pair in the NDJSON input'
    )


class QueryScope(BaseModel):
    """
    Per-query execution bounds.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    deadline_ms: int | None = Field(
        default=None,
        description="How long a shard may take before it is given up on, in\nmilliseconds, overriding the node's own budget for this query.\n\nA shard that misses it is skipped and reported in `coverage`, so a\ntight deadline degrades into an honest partial answer rather than\nan error — which is the point of setting one.\n\nCLAMPED to the node's configured timeout: a caller may ask for\nLESS time, never more. An unbounded deadline from a stranger would\npin a node's query slots open for as long as they liked.\n",
        ge=1,
    )


class Match(BaseModel):
    query: str


class MatchPhrase(BaseModel):
    query: str
    slop: int | None = Field(
        default=None,
        description='Positions between tokens allowed. Default 0 (exact phrase).',
        ge=0,
    )


class Term(BaseModel):
    value: str


class MultiMatch(BaseModel):
    """
    Multi-field full-text search. Desugars to a bool/should over
    per-field match queries. Requires FullTextSearchable capability
    on each listed field.

    """

    query: str = Field(
        ..., description='The text to search for across all listed fields.'
    )
    fields: list[str] = Field(
        ..., description='Fields to search. At least one required.'
    )


class Prefix(BaseModel):
    value: str


class Fuzziness(Enum):
    """
    Edit distance. "AUTO", 0, 1, or 2. Default "AUTO".
    """

    AUTO = 'AUTO'


class Fuzziness1(RootModel[int]):
    root: int = Field(
        ...,
        description='Edit distance. "AUTO", 0, 1, or 2. Default "AUTO".',
        ge=0,
        le=2,
    )


class Fuzzy(BaseModel):
    value: str = Field(..., description='The term to search for (will be analyzed).')
    fuzziness: Fuzziness | Fuzziness1 | None = Field(
        default=None, description='Edit distance. "AUTO", 0, 1, or 2. Default "AUTO".'
    )
    prefix_length: int | None = Field(
        default=None,
        description='Leading characters that must match exactly. Default 0.',
        ge=0,
    )
    transpositions: bool | None = Field(
        default=None, description='Count transpositions as single edit. Default true.'
    )


class Wildcard(BaseModel):
    value: str


class Exists(BaseModel):
    """
    Matches documents where the field has at least one value.
    """

    field: str


class RangeBounds(BaseModel):
    """
    Range bounds for filtering. Supports string, integer, and float values.
    Exclusive (gt/lt) and inclusive (gte/lte) bounds may not be combined
    on the same side (e.g. gt + gte is invalid). Numeric bounds are
    coerced to the field's storage type (e.g. float on an integer field
    uses ceil for lower / floor for upper).

    """

    gt: Any | None = Field(
        default=None, description='Exclusive lower bound (greater than)'
    )
    gte: Any | None = Field(
        default=None, description='Inclusive lower bound (greater than or equal)'
    )
    lt: Any | None = Field(
        default=None, description='Exclusive upper bound (less than)'
    )
    lte: Any | None = Field(
        default=None, description='Inclusive upper bound (less than or equal)'
    )


class GeoDistanceQuery(BaseModel):
    """
    Radius query around a point on a `geo_point` field. The centre and
    radius are flat fields — there is no nested `location` object and the
    radius is metres, not a unit-suffixed string.

    """

    field: str
    lat: float = Field(..., ge=-90.0, le=90.0)
    lon: float = Field(..., ge=-180.0, le=180.0)
    radius_meters: float = Field(..., description='Search radius in METRES.', gt=0.0)


class Relation(Enum):
    intersects = 'intersects'
    within = 'within'
    contains = 'contains'
    disjoint = 'disjoint'


class ShapeQuery(BaseModel):
    """
    Spatial-relation query over a `geo_shape`, cartesian `shape` or
    cartesian `point` field. Accepted under `geo_shape`, `shape` or
    `xy_shape` — the three keys are aliases and the relation applies to
    whatever spatial field is named.

    """

    field: str
    geometry: dict[str, Any] = Field(
        ..., description='GeoJSON geometry — the same format ingest accepts.'
    )
    relation: Relation | None = Relation.intersects


class GraphTraversalQuery(BaseModel):
    """
    Reachability over a `graph_edge` field.
    """

    field: str
    source: int = Field(..., description='Source node id.')
    hops: int | None = Field(default=None, ge=1)
    max_nodes: int | None = Field(default=None, ge=1)
    graph_index: str | None = Field(
        default=None,
        description='Cross-index join — traverse this index instead of the searched one.',
    )
    node_field: str | None = Field(
        default=None,
        description='Cross-index join — the filter field on the searched index.',
    )


class InformationContentQuery(BaseModel):
    """
    Information content of a taxonomy node (requires `taxonomy: true`).
    """

    field: str
    source: int


class ConceptSimilarityQuery(BaseModel):
    """
    Similarity between two taxonomy nodes (requires `taxonomy: true`).
    """

    field: str
    source: int
    target: int
    metric: str | None = None


class KnnQuery(BaseModel):
    """
    Approximate nearest-neighbour search over a `dense_vector` field.

    """

    field: str
    vector: list[float]
    k: int = Field(..., ge=1)
    ef: int | None = Field(
        default=None,
        description="Search-list size (Vamana `L`) — the candidate pool the graph walk\nkeeps, i.e. where the query sits on the recall/latency curve. The\nsame dial as OpenSearch `ef_search` / Elasticsearch\n`num_candidates`, and both of those names are accepted as aliases.\nOmitted means the engine's own heuristic. Clamped up to `k`.\n",
        ge=1,
    )
    oversample: float | None = Field(
        default=None,
        description='Rescore oversample factor for binary-quantized vector fields\n(e.g. 3.0). Ignored for unquantized fields.\n',
        ge=1.0,
    )


class Token(RootModel[list[float]]):
    root: list[float] = Field(..., min_length=1)


class LateInteractionQuery(BaseModel):
    """
    Late-interaction (ColBERT / MaxSim) retrieval over a multi_vector field.
    The query is itself a set of token vectors: each query token is scored
    against its best-matching document token and the maxima are summed, so a
    document that covers several query tokens across different vectors
    outranks one that matches a single token well. Executed inside the
    segment — only (document, score) leaves the shard.

    """

    field: str = Field(..., description='A multi_vector field.')
    tokens: list[Token] = Field(
        ...,
        description="Query token vectors, one inner array per token. Every token must be\nthe field's declared `dimensions` wide; a ragged set is rejected\nrather than reinterpreted.\n",
        min_length=1,
    )
    k: int = Field(..., ge=1)
    candidates_per_token: int | None = Field(
        default=None,
        description='Candidates pulled from the token graph per query token before the\nMaxSim rerank. Raising it trades latency for recall — the dial `ef`\nturns for single-vector kNN. Engine default when omitted.\n',
        ge=1,
    )
    ef: int | None = Field(
        default=None,
        description='Search-list size (Vamana L) for the per-token graph walk.',
        ge=1,
    )


class Weight(RootModel[float]):
    root: float = Field(..., ge=0.0)


class Technique(Enum):
    """
    Normalization technique to make heterogeneous scores comparable.
    """

    min_max = 'min_max'
    z_score = 'z_score'
    l2 = 'l2'
    rrf = 'rrf'


class ScoreNormalization(BaseModel):
    technique: Technique | None = Field(
        default=Technique.min_max,
        description='Normalization technique to make heterogeneous scores comparable.',
    )
    rank_constant: int | None = Field(
        default=None,
        description='Rank constant for RRF normalization. Default 60.',
        ge=1,
    )


class Technique1(Enum):
    """
    Combination technique to merge normalized scores.
    """

    arithmetic_mean = 'arithmetic_mean'
    harmonic_mean = 'harmonic_mean'
    geometric_mean = 'geometric_mean'
    rrf = 'rrf'


class ScoreCombination(BaseModel):
    technique: Technique1 | None = Field(
        default=Technique1.arithmetic_mean,
        description='Combination technique to merge normalized scores.',
    )
    rank_constant: int | None = Field(
        default=None, description='Rank constant for RRF combination. Default 60.', ge=1
    )


class Function(Enum):
    """
    Shape of the decay curve.
    """

    gaussian = 'gaussian'
    exponential = 'exponential'
    linear = 'linear'


class Decay(BaseModel):
    field: str = Field(
        ..., description='Stored field name (e.g. "timestamp", "updated_at")'
    )
    origin: Any | None = Field(
        default=None,
        description='Reference point. For dates: ISO 8601, epoch millis, or "now" (default).\n',
    )
    scale: str = Field(
        ...,
        description='Distance at which score equals `decay`. E.g. "7d", "12h", "30m".',
    )
    decay: float | None = Field(
        default=0.5, description='Score multiplier at `scale` distance.', ge=0.0, lt=1.0
    )
    offset: str | None = Field(
        default='0',
        description='Documents within this distance are not decayed. E.g. "1d".',
    )
    function: Function | None = Field(
        default=Function.exponential, description='Shape of the decay curve.'
    )


class Rerank(BaseModel):
    """
    Post-fusion decay re-ranking. Adjusts scores based on a stored field's
    distance from an origin point. Commonly used for recency decay.

    """

    decay: Decay


class Collapse(BaseModel):
    """
    Collapse (deduplicate) results by a stored field value. Keeps the
    top-scoring document per unique field value. Each surviving hit
    includes `_collapse_count` showing how many duplicates were removed.

    """

    field: str = Field(
        ..., description='Stored field name to group by (e.g. "domain", "category")'
    )


class Order(Enum):
    asc = 'asc'
    desc = 'desc'


class FieldGeoDistance(BaseModel):
    field: str
    lat: float
    lon: float
    order: Order | None = Order.asc


class SortClause1(BaseModel):
    """
    Geo-distance sort. Note the FLAT body — `field`/`lat`/`lon`, not a
    nested point object.


    Engine support is not universal: the tantivy engine refuses this
    with `400 unsupported_engine`. Where it IS served, ordering is
    done by the serving engine and cannot be re-ordered by the
    coordinator, so on an index with more than one claim the result is
    each claim's nearest documents rather than the corpus's.

    """

    field_geo_distance: FieldGeoDistance = Field(..., alias='_geo_distance')


class SortClause2(BaseModel):
    order: Order | None = Order.asc


class Graph(BaseModel):
    """
    Graph-traversal phase timing. Present only for a graph query.

    """

    plan: str
    reachability_ms: int
    materialize_ms: int
    segment_edges: int
    estimated_hits: int


class Verification(Enum):
    """
    This claim's verification state. `unverified` means could not
    check, which is NOT `failed`; conflating them either invents
    trust or discards good data.

    """

    verified = 'verified'
    unverified = 'unverified'
    failed = 'failed'
    local = 'local'


class ClaimRoute(BaseModel):
    """
    One claim's journey — who served it, how, and why not.
    """

    claim_id: int = Field(..., ge=0)
    served_by: str | None = Field(
        default=None,
        description='Hex node id of the peer that served this claim. Absent when\nnobody did.\n',
    )
    source: str = Field(
        ...,
        description='How the claim was answered — for example `local_primary`,\n`remote_replica` or `skipped`. Free-form: new sources may appear,\nso match the ones you care about and pass the rest through.\n',
    )
    verification: Verification = Field(
        ...,
        description="This claim's verification state. `unverified` means could not\ncheck, which is NOT `failed`; conflating them either invents\ntrust or discards good data.\n",
    )
    reason: str | None = Field(
        default=None,
        description='Why the claim was skipped — `timeout`, `unreachable`, and so on.\nAbsent when it was served.\n',
    )


class SkippedClaim(BaseModel):
    claim_id: int = Field(..., ge=0)
    reason: str


class Relation1(Enum):
    """
    `eq` means `value` is the exact number of matching documents.
    `gte` means it is a LOWER BOUND — currently the case whenever the
    engine did not count the corpus, which is the default. Treat a
    `gte` total as "at least this many", never as a result count.

    """

    eq = 'eq'
    gte = 'gte'


class TotalHits(BaseModel):
    """
    Hit-count summary. Always present — read `relation` before reading
    `value`, because the default is a LOWER BOUND, not a count.

    """

    value: int
    relation: Relation1 = Field(
        ...,
        description='`eq` means `value` is the exact number of matching documents.\n`gte` means it is a LOWER BOUND — currently the case whenever the\nengine did not count the corpus, which is the default. Treat a\n`gte` total as "at least this many", never as a result count.\n',
    )


class Hit(BaseModel):
    field_id: str = Field(..., alias='_id')
    field_score: float | None = Field(
        default=None,
        alias='_score',
        description='Relevance score. Null when sorting by field.',
    )
    field_source: dict[str, Any] | None = Field(
        default=None,
        alias='_source',
        description='Stored document fields. Present only if _source is\nrequested (default: true).\n',
    )
    field_version: str | None = Field(
        default=None,
        alias='_version',
        description='HLC document version, as the canonical wire string\n`wall_ms.counter.node_id_hex`. Omitted when no version is stored.\n',
    )
    sort: list[Any] | None = Field(
        default=None,
        description="This hit's sort values — the cursor to pass back as\n`search_after`. Present only when the request asked for an\nexplicit `sort`; array order matches the request's `sort`, with\n`_id` appended as the tiebreaker.\n",
    )
    field_per_leg_scores: list[float] | None = Field(
        default=None,
        alias='_per_leg_scores',
        description='Per-leg normalized scores from hybrid search. Index matches\nsub-query order. Missing legs show 0.0. Only present for\nhybrid queries.\n',
    )
    field_collapse_count: int | None = Field(
        default=None,
        alias='_collapse_count',
        description='Number of deduplicated documents sharing the same collapse\nfield value. Only present when collapse is active.\n',
        ge=0,
    )


class RepositorySpec(RootModel[FsRepositorySpec | S3RepositorySpec]):
    root: FsRepositorySpec | S3RepositorySpec = Field(
        ...,
        description="Where a repository's bytes live. `fs` is a directory; `s3` is any S3-compatible bucket, which includes AWS S3, MinIO, Ceph, Cloudflare R2 and Google Cloud Storage through its interoperability endpoint. Setting `encryption_key` seals every object written, so the store holds ciphertext only; losing that key loses the backup.\n",
        discriminator='type',
    )


class ErrorResponse(BaseModel):
    error: ErrorBody


class FieldDefinition(BaseModel):
    """
    Field options configure how a capability is implemented, not
    whether it exists. For example, `dimensions` and `distance_metric`
    affect dense_vector execution but do not change the field's
    capabilities.

    """

    type: FieldType
    dimensions: int | None = Field(
        default=None,
        description='Vector dimensionality (required for dense_vector and multi_vector).\nFor multi_vector this is the width of ONE token vector — the number\nof tokens is per-document and is never declared in the mapping.\n',
        ge=1,
    )
    distance_metric: DistanceMetric | None = Field(
        default=DistanceMetric.cosine,
        description='Distance function (dense_vector and multi_vector only)',
    )
    quantization: Quantization | None = Field(
        default=Quantization.none,
        description='On-disk vector quantization (dense_vector only). `none` stores\nfloat32; `int8` is ~4x smaller, `int4` ~8x, `binary` ~32x.\n',
    )
    taxonomy: bool | None = Field(
        default=False,
        description='Taxonomy DAG mode for graph_edge fields — precomputes the\ntransitive closure at flush. Always present on responses,\nincluding for field types where it has no effect.\n',
    )
    format: Format | None = Field(
        default=None,
        description='Date format (date fields only). Default: strict_date_optional_time.\nControls output format in _source. Ingest always accepts both\nISO-8601 strings (nanosecond precision) and epoch milliseconds\nregardless of format. Internal precision is nanoseconds.\n',
    )


class BulkIndexResponse(BaseModel):
    items: list[BulkItemResult]
    errors: bool = Field(..., description='True if any item failed')
    ack: Ack1 = Field(
        ...,
        description='Durability level reached for the whole batch. Always present.\n',
    )
    timed_out: bool | None = Field(
        default=None,
        description='True if `wait_for` timed out before the requested level was reached.',
    )


class BulkStreamResponse(BaseModel):
    took: int = Field(..., description='Time in milliseconds')
    items: list[BulkStreamItem]
    errors: bool = Field(..., description='True if any item failed')
    ack: str = Field(..., description='Durability acknowledgment level')
    timed_out: bool | None = Field(
        default=None, description='True if wait_for=durable timed out'
    )


class FanOutProfile(BaseModel):
    """
    Where the query actually went, and what came back.

    A distributed search that cannot tell you which peers answered is
    asking to be trusted rather than audited. The node already knows all
    of this while answering; setting `profile: true` is what stops it
    being discarded at the HTTP boundary.

    The four verification counts partition `claims` exactly:
    `verified + unverified + failed_verification + local` equals its
    length. `unverified` is its own count on purpose — a claim nobody
    could check is not a claim that passed.

    """

    nodes_contacted: int = Field(
        ..., description='Distinct nodes this query was sent to.', ge=0
    )
    nodes_responded: int = Field(
        ...,
        description='Distinct nodes that answered. Fewer than contacted means a peer\nwent silent — the case `partial` summarises and this attributes.\n',
        ge=0,
    )
    deadline_ms: int = Field(
        ...,
        description='The per-shard deadline this query actually ran under, after the\nnode clamped `scope.deadline_ms` to its own budget.\n',
        ge=0,
    )
    claims: list[ClaimRoute] = Field(
        ..., description='One row per claim the query addressed.'
    )
    verified_claims: int = Field(
        ...,
        description='Claims whose documents were PROVEN authentic against an anchor\nthis node holds independently of the responder.\n',
        ge=0,
    )
    unverified_claims: int = Field(
        ...,
        description='Claims this node could not check — no proof arrived, or there is\nno authenticated index for them. Reported separately from\nverified because a silent pass that reads as a real check is the\nfailure this whole path exists to avoid.\n',
        ge=0,
    )
    failed_verification_claims: int = Field(
        ...,
        description='Claims whose proof did NOT check out. Their documents were not\nserved.\n',
        ge=0,
    )
    local_claims: int = Field(
        ...,
        description='Claims this node served itself. There is no remote party to\nattest to, so there is nothing to verify — counted separately so\nthe four states account for every claim and a reader can see\nthat they do.\n',
        ge=0,
    )


class SearchCoverage(BaseModel):
    """
    Auditable claim-level completeness for this search.
    """

    expected_claims: int = Field(..., description='Claims the index resolves to.', ge=0)
    served_claims: int = Field(..., description='Claims that served this query.', ge=0)
    skipped_claims: list[SkippedClaim] = Field(
        ...,
        description='Claims omitted from the result and the reason each was skipped.',
    )


class HitsContainer(BaseModel):
    total: TotalHits
    hits: list[Hit]


class IndexSchema(BaseModel):
    fields: dict[str, FieldDefinition] = Field(
        ...,
        description='Field name → field definition mapping.\n\n**Four field names are reserved and cannot be declared**:\n`id`, `version`, `title` and `canonical_url`. They are owned by\nthe document envelope — `id`/`version` are identity, `title`/\n`canonical_url` are folded into the authenticated record from the\ndocument header — so declaring one is rejected at index creation\nwith a `validation_error`, on every engine.\n\n`title` in particular is a name most search schemas reach for\nfirst. Use `name`, `headline` or `subject` instead, and put the\ncanonical title in the document header where the authenticated\nrecord picks it up.\n',
    )


class IndexMetadata(BaseModel):
    name: str
    schema_: IndexSchema = Field(..., alias='schema')
    engine_binding: str | None = Field(
        default=None,
        description="The engine this index is bound to (e.g. `tantivy`). Binding is\ndecided at creation from the schema's field types and is\nimmutable afterwards.\n",
    )
    created_at: AwareDatetime | None = None
    claim_count: int = Field(
        ...,
        description='Number of claim units this index is spread across — the\ndenominator `coverage.expected_claims` is measured against.\n',
        ge=1,
    )


class IndexListResponse(BaseModel):
    indexes: list[IndexMetadata]
    next_after: str | None = Field(
        default=None,
        description='Cursor for the next page. Absent once the listing is complete, so a client stops when the field stops appearing.\n',
    )


class SearchProfile(BaseModel):
    """
    Query execution profile. Present only when the request set
    `profile: true`, and only when there was something to report.

    Both members are OPTIONAL and each appears when it applies. `graph`
    is emitted only for a graph traversal, so the ordinary case — any
    other query with `profile: true` — carries `fan_out` alone. A client
    that treats `graph` as guaranteed rejects the common response.

    """

    graph: Graph | None = Field(
        default=None,
        description='Graph-traversal phase timing. Present only for a graph query.\n',
    )
    fan_out: FanOutProfile | None = None


class CreateIndexRequest(BaseModel):
    schema_: IndexSchema = Field(..., alias='schema')


class SearchResponse(BaseModel):
    hits: HitsContainer
    took: int = Field(..., description='Query execution time in milliseconds')
    partial: bool = Field(
        ...,
        description='True if the result set may be incomplete due to node\nfailures or timeouts. Clients that require complete retrieval\nmust reject partial responses.\n',
    )
    coverage: SearchCoverage
    profile: SearchProfile | None = None


class SearchRequest(BaseModel):
    query: Query | None = None
    sort: list[str | SortClause1 | dict[str, SortClause2]] | None = Field(
        default=None,
        description='Sort order. Defaults to `_score` descending if omitted.\n\n\n**One sort field.** Sorting by two or more fields is not\nimplemented and is refused with `400 unsupported_engine` rather\nthan partially applied. An `_id` tiebreaker is always appended, so\nthe order is total and stable across claims and repeats.\n\n\n**Sortable types:** integer/long/float/double, date, and boolean.\nKeyword and text fields are NOT sortable and are refused with\n`400 unsupported_capability`. `_score` is always accepted;\n`_geo_distance` parses but is engine-dependent — see `SortClause`.\n',
    )
    from_: int | None = Field(
        default=0,
        alias='from',
        description='Pagination offset. Bounded by `from + size <= 10000`, and the cost\ngrows with the offset because every claim must collect `from + size`\nrows. Use `search_after` to walk a large result set.\n',
        ge=0,
    )
    search_after: list[Any] | None = Field(
        default=None,
        description="Keyset pagination cursor: pass the `sort` array from the last hit of\nthe previous page to get the rows after it. Requires an explicit\n`sort`, and `from` is ignored when present.\n\n\nPrefer this over `from` for anything deep. The cursor is pushed down\nto each claim as a range on the first sort key, so a page costs the\nsame whether it is the first or the ten-thousandth, and it is stable\nunder concurrent writes in a way an offset is not.\n\n\nA caveat worth knowing: documents sharing the cursor's first sort\nvalue are fetched and then discarded, so sorting on a field with\nvery long runs of one value can stall a walk. Sort on something\nreasonably distinct, or add a second sort key.\n",
    )
    size: int | None = Field(
        default=10, description='Maximum number of hits to return', ge=0, le=10000
    )
    field_source: bool | list[str] | None = Field(
        default=None,
        alias='_source',
        description='Control _source field inclusion. `true` (default) returns\nfull source, `false` excludes it, array selects fields.\n',
    )
    rerank: Rerank | None = None
    collapse: Collapse | None = None
    track_total_hits: bool | None = Field(
        default=None,
        description='Ask for an exact `hits.total` even when `size` is 0 — what a graph\ntraversal that only wants a count asks for. It is a REQUEST, not a\nguarantee: engines that cannot count the corpus still answer\n`relation: gte`, so read `hits.total.relation` before trusting\n`hits.total.value`.\n',
    )
    profile: bool | None = Field(
        default=None,
        description="Include a `profile` block in the response: the fan-out — which\npeer served each claim, which were skipped and why, how many\nnodes answered and what each claim's proof came to — and, for a\ngraph traversal, phase timing (reachability vs materialize).\n\nEach member of `profile` appears only when it applies, so the\nusual response carries `fan_out` without `graph`. The node\ncomputes none of this unless you ask.\n",
    )
    verify: bool | None = Field(
        default=None,
        description='Require tamper evidence for this search.\n\nEvery served claim must be PROVEN — a proof binding to an anchor\nthe node holds independently of whoever served it. A claim nobody\ncould check then counts against completeness exactly as an\nunanswered one does, so `verify: true` with `partial: false` means\nevery row returned was proven, and `partial: true` reports which\nclaims were not, in `coverage.skipped_claims`.\n\nDistinct from asking for complete COVERAGE: that asks whether\nevery claim answered, this asks whether every answer was proven.\n',
    )
    scope: QueryScope | None = None


class Query(BaseModel):
    """
    Query DSL. Exactly one top-level key specifying the query type.
    ES-inspired shape for familiarity, but all behavior is explicit.

    """

    match: dict[str, str | Match] | None = Field(
        default=None,
        description='Full-text analyzed search. Requires FullTextSearchable\ncapability on the target field.\n',
    )
    match_phrase: dict[str, str | MatchPhrase] | None = Field(
        default=None,
        description='Phrase match — tokens must appear consecutively. Optional slop\nallows intervening tokens. Requires FullTextSearchable capability.\n',
    )
    term: dict[str, str | Term] | None = Field(
        default=None,
        description='Exact-match term lookup. Requires ExactMatchable capability.\n',
    )
    range: dict[str, RangeBounds] | None = Field(
        default=None,
        description='Range query on numeric, date, or keyword fields. Requires\nRangeQueryable capability. Date bounds accept ISO-8601 strings\n(nanosecond precision), epoch milliseconds, or date math\nexpressions (e.g. "now-7d").\n',
    )
    bool: BoolQuery | None = None
    match_all: dict[str, Any] | None = Field(
        default=None, description='Match all documents. No field requirement.'
    )
    multi_match: MultiMatch | None = Field(
        default=None,
        description='Multi-field full-text search. Desugars to a bool/should over\nper-field match queries. Requires FullTextSearchable capability\non each listed field.\n',
    )
    geo_distance: GeoDistanceQuery | None = None
    geo_shape: ShapeQuery | None = None
    shape: ShapeQuery | None = None
    xy_shape: ShapeQuery | None = None
    knn: KnnQuery | None = None
    late_interaction: LateInteractionQuery | None = None
    hybrid: HybridQuery | None = None
    prefix: dict[str, str | Prefix] | None = Field(
        default=None,
        description='Prefix query — matches terms starting with the given value.\nSupports both text and keyword fields. Not analyzed.\n',
    )
    fuzzy: dict[str, Fuzzy] | None = Field(
        default=None,
        description='Fuzzy term query with Levenshtein edit distance. Requires\nFullTextSearchable capability. "AUTO" fuzziness maps to\ndistance 0 for terms <=2 chars, 1 for 3-5, 2 for >=6.\n',
    )
    wildcard: dict[str, str | Wildcard] | None = Field(
        default=None,
        description='Wildcard pattern match with `*` (any run) and `?` (one character).\nNot analyzed.\n',
    )
    exists: Exists | None = Field(
        default=None,
        description='Matches documents where the field has at least one value.',
    )
    mmr: MmrQuery | None = None
    graph_traversal: GraphTraversalQuery | None = None
    information_content: InformationContentQuery | None = None
    concept_similarity: ConceptSimilarityQuery | None = None


class BoolQuery(BaseModel):
    must: list[Query] | None = None
    should: list[Query] | None = None
    must_not: list[Query] | None = None
    filter: list[Query] | None = Field(
        default=None, description='Non-scoring filter clauses'
    )


class MmrQuery(BaseModel):
    """
    Maximal Marginal Relevance diversity rerank over an inner query,
    using a `dense_vector` field for the diversity similarity.

    """

    query: Query
    field: str = Field(
        ..., description='The `dense_vector` field supplying the diversity similarity.'
    )
    lambda_: float | None = Field(
        default=0.5,
        alias='lambda',
        description='1.0 = pure relevance, 0.0 = pure diversity. Clamped at execution.',
    )
    candidates: int | None = Field(
        default=100,
        description='How many inner results to consider before reranking.',
        ge=1,
    )


class HybridQuery(BaseModel):
    """
    Multi-modal hybrid search with score normalization and combination.
    Each sub-query is executed independently; the coordinator normalizes
    and combines scores. Explicit sort is not supported — results are
    always ranked by combined score.

    """

    queries: list[Query] = Field(
        ...,
        description='Sub-queries to execute. Each can be any query type except hybrid (no nesting).',
        min_length=1,
    )
    weights: list[Weight] | None = Field(
        default=None,
        description='Per-sub-query weights (length must match queries). Default 1.0 each.',
    )
    score_normalization: ScoreNormalization | None = None
    score_combination: ScoreCombination | None = None


SearchRequest.model_rebuild()
Query.model_rebuild()
